<?xml version="1.0"?>
<robot name="sensor_contact" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="sensor_contact" params="name parent *origin body_length body_width body_height">
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link">
      <inertial>
        <mass value="0.0001" />
          <origin xyz="0 0 0" rpy="0 0 0" />
          <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
      </inertial>

      <collision name="erle_box_collision">
        <geometry>
          <box size="${100 * body_length} ${100 * body_width} ${100 * body_height}" /> <!-- [m] [m] [m] -->
        </geometry>
      </collision>
    </link>
  	
    <gazebo reference="${name}_link">
      <sensor name="erle_contact_sensor" type="contact">
        <always_on>true</always_on>
        <update_rate>30.0</update_rate>
        <contact>
          <collision>erle_box_collision</collision>
        </contact>
        <plugin name="erle_contact_bumper" filename="libgazebo_ros_bumper.so">
          <bumperTopicName>erle_contact_sensor_state</bumperTopicName>
          <frameName>erle_contact</frameName>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>